export const keyMap: Record<string, string> = {
  ArrowDown: "Down",
  ArrowLeft: "Left",
  ArrowRight: "Right",
  ArrowUp: "Up",
  Enter: "Start",
  a: "A",
  b: "B",
  c: "C",
  l: "L",
  m: "Mode",
  r: "R",
  s: "Select",
  x: "X",
  y: "Y",
  z: "Z",
};
