import perfectionist from "eslint-plugin-perfectionist";
import playwright from "eslint-plugin-playwright";
import regexp from "eslint-plugin-regexp";
import { defineConfig } from "oxlint";

const off = (rules: string[]): Record<string, "off"> =>
  Object.fromEntries(rules.map((rule) => [rule, "off"]));

export default defineConfig({
  categories: {
    correctness: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  ignorePatterns: ["public", "scripts", "*.config.js", "oxlint.config.mts"],
  jsPlugins: [
    "eslint-plugin-no-relative-import-paths",
    "eslint-plugin-perfectionist",
    "eslint-plugin-react-hooks-addons",
    "eslint-plugin-regexp",
  ],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
    typeAware: true,
  },
  overrides: [
    {
      files: ["__tests__/**"],
      plugins: ["jest"],
      rules: off([
        "jest/no-conditional-in-test",
        "jest/no-hooks",
        "jest/prefer-ending-with-an-expect",
        "jest/prefer-expect-assertions",
        "jest/prefer-importing-jest-globals",
      ]),
    },
    {
      files: ["e2e/**"],
      jsPlugins: ["eslint-plugin-playwright"],
      rules: {
        ...playwright.configs["flat/recommended"].rules,
        ...off([
          "playwright/consistent-spacing-between-blocks",
          "playwright/expect-expect",
          "playwright/no-conditional-in-test",
          "playwright/no-duplicate-hooks",
          "playwright/no-skipped-test",
          "playwright/prefer-locator",
        ]),
      },
    },
  ],
  plugins: [
    "import",
    "jsx-a11y",
    "nextjs",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
  ],
  rules: {
    ...perfectionist.configs["recommended-alphabetical"].rules,
    ...regexp.configs["flat/recommended"].rules,
    curly: ["error", "multi-line"],
    "import/consistent-type-specifier-style": ["error", "prefer-inline"],
    "new-cap": ["error", { capIsNew: false }],
    "no-console": ["error", { allow: ["info", "error", "time", "timeEnd"] }],
    "no-else-return": ["error", { allowElseIf: false }],
    "no-implicit-coercion": ["error", { boolean: false }],
    "no-param-reassign": [
      "error",
      {
        ignorePropertyModificationsFor: ["acc", "accumulator", "ctx", "e"],
        props: true,
      },
    ],
    "no-relative-import-paths/no-relative-import-paths": "error",
    "no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        fix: { imports: "safe-fix" },
        ignoreRestSiblings: true,
        varsIgnorePattern: "^_",
      },
    ],
    "one-var": ["error", "never"],
    "perfectionist/sort-imports": [
      "error",
      {
        groups: [
          "builtin",
          "external",
          "internal",
          ["parent", "sibling", "index"],
          "unknown",
        ],
        internalPattern: [
          "^(__tests__|components|contexts|e2e|hooks|pages|public|styles|utils)/",
        ],
        newlinesBetween: 0,
      },
    ],
    "perfectionist/sort-jsx-props": [
      "error",
      {
        customGroups: [
          {
            elementNamePattern: "^(children|dangerouslySetInnerHTML|key|ref)$",
            groupName: "reserved",
          },
        ],
        groups: ["reserved", "unknown", "shorthand-prop"],
      },
    ],
    "prefer-destructuring": [
      "error",
      {
        AssignmentExpression: { array: true, object: false },
        VariableDeclarator: { array: false, object: true },
      },
    ],
    "react-hooks-addons/no-unused-deps": "error",
    "react/function-component-definition": [
      "error",
      {
        namedComponents: "arrow-function",
        unnamedComponents: "arrow-function",
      },
    ],
    "react/jsx-filename-extension": [
      "error",
      { allow: "as-needed", extensions: [".tsx"] },
    ],
    "typescript/explicit-function-return-type": [
      "error",
      { allowExpressions: true },
    ],
    "typescript/switch-exhaustiveness-check": [
      "error",
      { considerDefaultExhaustiveForUnions: true },
    ],
    "typescript/restrict-template-expressions": [
      "error",
      { allowNumber: true },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "unicorn/import-style": ["error", { styles: { path: { named: true } } }],
    "unicorn/no-useless-undefined": ["error", { checkArguments: false }],
    "unicorn/switch-case-braces": ["error", "avoid"],
    // Bans language features or conventions this codebase is built on
    ...off([
      "import/exports-last",
      "import/group-exports",
      "import/no-default-export",
      "import/no-named-export",
      "import/no-namespace",
      "import/no-nodejs-modules",
      "import/prefer-default-export",
      "import/unambiguous",
      "no-plusplus",
      "no-ternary",
      "no-undefined",
      "oxc/no-async-await",
      "oxc/no-optional-chaining",
      "oxc/no-rest-spread-properties",
      "promise/avoid-new",
      "promise/prefer-await-to-callbacks",
      "promise/prefer-await-to-then",
      "react/jsx-no-literals",
      "react/jsx-props-no-spreading",
      "react/react-in-jsx-scope",
      "typescript/consistent-type-definitions",
      "typescript/no-import-type-side-effects",
      "unicorn/filename-case",
      "unicorn/no-array-for-each",
      "unicorn/no-array-reduce",
      "unicorn/no-await-expression-member",
    ]),
    // Arbitrary size/shape limits
    ...off([
      "capitalized-comments",
      "complexity",
      "id-length",
      "import/max-dependencies",
      "init-declarations",
      "max-depth",
      "max-lines",
      "max-lines-per-function",
      "max-params",
      "max-statements",
      "no-inline-comments",
      "no-magic-numbers",
      "no-nested-ternary",
      "prefer-named-capture-group",
      "react/forbid-component-props",
      "react/jsx-max-depth",
      "react/no-multi-comp",
      "require-unicode-regexp",
      "unicorn/max-nested-calls",
      "unicorn/no-nested-ternary",
      "unicorn/numeric-separators-style",
    ]),
    // Newer than browserslist floor (Chrome 84 / Safari 13.1)
    ...off([
      "unicorn/no-array-reverse",
      "unicorn/no-array-sort",
      "unicorn/prefer-at",
      "unicorn/prefer-global-this",
      "unicorn/prefer-node-protocol",
      "unicorn/prefer-string-replace-all",
    ]),
    // Too noisy for the value, or wrong for this code
    ...off([
      "class-methods-use-this",
      "import/no-cycle",
      "import/no-named-as-default",
      "jsx-a11y/control-has-associated-label",
      "jsx-a11y/no-autofocus",
      "jsx-a11y/prefer-tag-over-role",
      "nextjs/no-img-element",
      "no-redeclare",
      "no-underscore-dangle",
      "oxc/no-map-spread",
      "perfectionist/sort-classes",
      "perfectionist/sort-intersection-types",
      "perfectionist/sort-maps",
      "perfectionist/sort-modules",
      "perfectionist/sort-sets",
      "perfectionist/sort-switch-case",
      "promise/always-return",
      "promise/catch-or-return",
      "promise/no-nesting",
      "promise/no-promise-in-callback",
      "react/display-name",
      "react/iframe-missing-sandbox",
      "react/jsx-handler-names",
      "react/only-export-components",
      "require-await",
      "sort-imports",
      "sort-keys",
      "typescript/ban-types",
      "typescript/explicit-module-boundary-types",
      "typescript/no-confusing-void-expression",
      "typescript/no-dynamic-delete",
      "typescript/no-floating-promises",
      "typescript/no-invalid-void-type",
      "typescript/no-misused-promises",
      "typescript/no-misused-spread",
      "typescript/no-unsafe-type-assertion",
      "typescript/no-useless-default-assignment",
      "typescript/non-nullable-type-assertion-style",
      "typescript/prefer-nullish-coalescing",
      "typescript/prefer-readonly-parameter-types",
      "typescript/promise-function-async",
      "typescript/strict-boolean-expressions",
      "typescript/strict-void-return",
      "typescript/unbound-method",
      "typescript/use-unknown-in-catch-callback-variable",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-array-callback-reference",
      "unicorn/number-literal-case",
      "unicorn/prefer-number-coercion",
      "unicorn/require-post-message-target-origin",
    ]),
    // React Compiler rules (not adopted yet)
    ...off([
      "react/exhaustive-effect-dependencies",
      "react/hooks",
      "react/immutability",
      "react/invariant",
      "react/memo-dependencies",
      "react/preserve-manual-memoization",
      "react/purity",
      "react/refs",
      "react/rule-suppression",
      "react/set-state-in-effect",
      "react/todo",
    ]),
  },
});
