const config = {
  animationSpeed: 1,
  backgroundColor: [0, 0, 0],
  baseBrightness: -0.5,
  baseContrast: 1.1,
  bloomSize: 0.4,
  bloomStrength: 0.7,
  brightnessDecay: 1,
  brightnessOverride: 0,
  brightnessThreshold: 0,
  cursorColor: [1.5, 2, 0.9],
  cycleFrameSkip: 1,
  cycleSpeed: 0.03,
  density: 1,
  ditherMagnitude: 0.05,
  fallSpeed: 0.3,
  font: "matrixcode",
  forwardSpeed: 0.25,
  glintBrightness: -1.5,
  glintColor: [1, 1, 1],
  glintContrast: 2.5,
  glyphEdgeCrop: 0,
  glyphHeightToWidth: 1,
  glyphMSDFURL: "/System/Matrix/assets/matrixcode_msdf.png",
  glyphSequenceLength: 57,
  glyphTextureGridSize: [8, 8],
  glyphVerticalSpacing: 1,
  hasBaseTexture: false,
  hasGlintTexture: false,
  hasThunder: false,
  highPassThreshold: 0.1,
  isPolar: false,
  isolateCursor: true,
  isolateGlint: false,
  isometric: false,
  loops: false,
  numColumns: 80,
  paletteEntries: [
    {
      at: 0,
      hsl: [0.3, 0.9, 0],
    },
    {
      at: 0.2,
      hsl: [0.3, 0.9, 0.2],
    },
    {
      at: 0.7,
      hsl: [0.3, 0.9, 0.7],
    },
    {
      at: 0.8,
      hsl: [0.3, 0.9, 0.8],
    },
  ],
  raindropLength: 0.75,
  renderer: "webgpu",
  resolution: 0.75,
  rippleScale: 30,
  rippleSpeed: 0.2,
  rippleThickness: 0.2,
  skipIntro: true,
  slant: 0,
  useCamera: false,
  useHalfFloat: false,
  useHoloplay: false,
  volumetric: false,
};

export default config;
