const config = {
  animationSpeed: 1,
  backgroundColor: [0, 0, 0],
  baseBrightness: -0.5,
  baseContrast: 1.1,
  bloomSize: 0.4,
  bloomStrength: 0.7,
  brightnessDecay: 1,
  brightnessOverride: 0,
  brightnessThreshold: 0,
  cursorColor: [1, 3, 1.5],
  cycleFrameSkip: 4,
  cycleSpeed: 0.02,
  density: 1,
  ditherMagnitude: 0.05,
  fallSpeed: 0.3,
  font: "matrixcode",
  forwardSpeed: 0.25,
  glintBrightness: -1.5,
  glintColor: [1, 1, 1],
  glintContrast: 2.5,
  glyphEdgeCrop: 0,
  glyphHeightToWidth: 1,
  glyphMSDFURL: "/System/Matrix/assets/matrixcode_msdf.png",
  glyphSequenceLength: 57,
  glyphTextureGridSize: [8, 8],
  glyphVerticalSpacing: 1,
  hasBaseTexture: false,
  hasGlintTexture: false,
  hasThunder: false,
  highPassThreshold: 0,
  isPolar: false,
  isolateCursor: true,
  isolateGlint: false,
  isometric: false,
  loops: false,
  numColumns: 100,
  paletteEntries: [
    { at: 0, hsl: [0.4, 0.8, 0] },
    { at: 0.5, hsl: [0.4, 0.8, 0.5] },
    { at: 1, hsl: [0.4, 0.8, 1] },
  ],
  raindropLength: 1.5,
  renderer: "webgl",
  resolution: 1,
  rippleScale: 30,
  rippleSpeed: 0.2,
  rippleThickness: 0.2,
  slant: 0,
  useCamera: false,
  useHalfFloat: false,
  useHoloplay: false,
  volumetric: false,
};

export default config;
