"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var StyledFiles = styled_components_1.default.figure(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  ol {\n    display: flex;\n    flex-flow: row wrap;\n    gap: 5px;\n    max-height: 97px;\n    overflow-y: hidden;\n    padding-top: 9px;\n\n    li {\n      background-color: rgba(60, 60, 60, 85%);\n      border: 1px solid rgba(75, 75, 75, 85%);\n      border-radius: 15px;\n      display: flex;\n      padding: 4px 10px;\n      place-content: center;\n      place-items: center;\n      white-space: nowrap;\n\n      h2 {\n        bottom: 1px;\n        display: block;\n        font-size: 12px;\n        font-weight: 400;\n        height: 16px;\n        max-width: 235px;\n        overflow: hidden;\n        padding-top: 1px;\n        place-items: center;\n        position: relative;\n        text-overflow: ellipsis;\n      }\n\n      picture,\n      img {\n        height: 16px;\n        margin-right: 5px;\n        width: 16px;\n      }\n\n      &:hover {\n        background-color: rgba(80, 80, 80, 85%);\n      }\n    }\n  }\n"], ["\n  ol {\n    display: flex;\n    flex-flow: row wrap;\n    gap: 5px;\n    max-height: 97px;\n    overflow-y: hidden;\n    padding-top: 9px;\n\n    li {\n      background-color: rgba(60, 60, 60, 85%);\n      border: 1px solid rgba(75, 75, 75, 85%);\n      border-radius: 15px;\n      display: flex;\n      padding: 4px 10px;\n      place-content: center;\n      place-items: center;\n      white-space: nowrap;\n\n      h2 {\n        bottom: 1px;\n        display: block;\n        font-size: 12px;\n        font-weight: 400;\n        height: 16px;\n        max-width: 235px;\n        overflow: hidden;\n        padding-top: 1px;\n        place-items: center;\n        position: relative;\n        text-overflow: ellipsis;\n      }\n\n      picture,\n      img {\n        height: 16px;\n        margin-right: 5px;\n        width: 16px;\n      }\n\n      &:hover {\n        background-color: rgba(80, 80, 80, 85%);\n      }\n    }\n  }\n"])));
exports.default = StyledFiles;
var templateObject_1;
