// `fly help`: what this thing actually is, and how far the simulation goes.
//
// Every number here is checked against the code and the data it loads. If a
// constant moves, this text moves with it — an inaccurate claim about the
// fly is worse than no claim at all.

export const FLY_HELP: readonly string[] = [
  "fly - a desktop pet whose brain is the real Drosophila melanogaster",
  "connectome, wired from the FlyWire FAFB v783 reconstruction.",
  "",
  "USAGE",
  "  fly [N]            Spawn N flies (default 1, max 5).",
  "  fly 0 | fly kill   Remove every fly.",
  "  fly scare          Loom into every fly's eyes at once.",
  "  fly audio on|off   Audible wingbeats (default off).",
  "  fly help           Show this text.",
  "  gnat               Alias for fly.",
  "",
  "BRAIN",
  "  - 9,907 real neurons and 197,074 connections carrying 3.1 million",
  "    real synapses, in 1.17 MB. The wiring is measured, not invented.",
  "  - Leaky integrate-and-fire, stepped at 1 kHz: 20 ms membrane, 2 ms",
  "    refractory, 4 ms inhibitory delay. About 1.3 ms per frame per fly.",
  "  - The wiring is compiled once and shared; the voltages, the noise and",
  "    the learned weights are each fly's own. Five at once - the cap is a",
  "    deliberate trade, five bigger brains over six smaller ones.",
  "  - 591 looming detectors: LC4 and LPLC2 wire onto the 2 DNp01 giant",
  "    fibres, the real escape command neuron; LC6 and LC16 act elsewhere.",
  "  - Compass: 47 EPG ring cells, 42 PEN shifters, 42 Delta7, 20 PEG.",
  "  - Mushroom body: every one of the brain's 5,177 Kenyon cells - gamma,",
  "    alpha/beta and alpha-prime/beta-prime, the last being the ones that",
  "    memory acquisition actually needs - plus 285 projection neurons,",
  "    96 MBONs, 16 PPL1 and 120 PAM dopamine cells.",
  "  - Plus 61 PFN and 18 hDeltaB vector cells, 127 LC11, 237 LC10a, and",
  "    the MDN, DNp09, DNg11, DNa01/02 and escape-wing command neurons.",
  "",
  "SEES",
  "  - About 270 degrees of view between the two eyes, leaving a 90 degree",
  "    blind cone behind it. You can sneak up on it from there, and it is",
  "    a real blind spot, not a fudge.",
  "  - Looming is computed per eye, so an approaching window or a lunging",
  "    cursor swells on one side and it escapes toward the other.",
  "  - A window has to be closing to loom; parked, it is just scenery. A",
  "    cursor sitting on top of it does register, and then adapts away.",
  "  - Tells apart what it stands on and what lies ahead: desktop icons by",
  "    name, windows by title, sheep, the taskbar, and bare wallpaper.",
  "  - Samples your actual wallpaper pixels (48x27, brightness only) and",
  "    steers up the gradient: toward light awake, toward dark when sleepy.",
  "  - Cannot read. A label is an identity to it, never a word.",
  "  - Cannot see colour. Only luminance.",
  "  - Has no privileged access to your pointer. It knows only what its own",
  "    retinas report, and infers every threat direction from that.",
  "",
  "HEARS AND FEELS",
  "  - Hears playing media as substrate vibration, read from Webamp's own",
  "    state and the DOM's audio and video elements. Never a microphone.",
  "  - Grows restless near a loud window, and remembers it as a bad place.",
  "  - A click within 260 px is a tap felt through the substrate; within",
  "    32 px it is contact, straight into the giant fibre.",
  "  - Feels its own gait: leg rhythm returns through ascending neurons,",
  "    and walking speed drives the PFN vector cells.",
  "  - Feels a neighbour's takeoff, and a window or menu popping open.",
  "",
  "LEARNS AND REMEMBERS",
  "  - Objects arrive as projection-neuron combinations. The sparse Kenyon",
  "    cell code (~5% of cells) emerges from the real claws, not from us.",
  "  - Swat it while it is watching something and PPL1 dopamine depresses",
  "    that code's synapses - measurably, and only that code's. Whether one",
  "    swat is enough to visibly turn the fly off an icon is not something",
  "    to promise: the depression is real, the behavioural readout on top",
  "    of it is noisy. Its verdict is relative, meaning worse than the",
  "    other things this fly looks at, not worse than silence.",
  "  - A 3 second eligibility trace means it blames whatever it saw just",
  "    before the swat. Real trace conditioning, unfairness included.",
  "  - Calm grooming teaches the opposite, through the PAM reward pathway.",
  "  - Forgetting is slow: depressed synapses creep back over minutes.",
  "  - Maps where things happened, 12x7 across the screen. Danger fades",
  "    over ~70 s, comfort over ~150 s. It stops landing where it got hurt.",
  "  - Habituates: the tenth appearance of a window startles it about a",
  "    third as hard as the first did.",
  "  - Holds its last 24 sightings, and how familiar each thing has become.",
  "",
  "NAVIGATES",
  "  - Its heading bump persists in the dark: it wobbles moment to moment",
  "    but holds its bearing - steadier, in fact, than the real animal's,",
  "    a stickiness that comes with the small ring. The ring order came",
  "    from the wiring.",
  "  - The bump lags a fast turn: this is 151 of the compass cells, not the",
  "    whole central complex, so the heading it keeps is a rough one.",
  "  - Rest somewhere long enough and it becomes home. It integrates its",
  "    wandering in that compass frame and walks the vector back, drift",
  "    and all - which is why it often arrives a little off.",
  "",
  "BODY",
  "  - Walks at about 7 mm/s, legs turning over around 10 Hz, bursting",
  "    past 11 mm/s - every one of those measured against the real animal",
  "    rather than eyeballed.",
  "  - Mostly hops rather than travels: a typical flight is six or seven",
  "    centimetres - an eighth of the screen - and mostly taking off and",
  "    landing. Startle it and that becomes a bolt at full flight speed,",
  "    two and a half times as fast and half again as far.",
  "  - It is drawn about twice life size, because a true-scale fruit fly",
  "    would be nine pixels long and impossible to see or catch. Speed is",
  "    set by the desktop's scale, not the fly's, so it crosses the screen",
  "    at the pace a real one crosses a desk.",
  "  - Walks in runs of about two seconds and pauses for about one and a",
  "    half. It does not vibrate between standing and walking.",
  "  - Flies in a straight line. A whole fly does not weave: real ones",
  "    cross a room in straight runs broken by sharp turns, and the only",
  "    constant wobble is the wingbeat, far too small and fast to see. Torn",
  "    wings are the exception - the lift really is lopsided then.",
  "  - Tripod gait on six two-jointed legs. Wings fold flat over the",
  "    abdomen at rest and sweep out for flight; halteres beat behind them.",
  "  - Drawn from the anatomy: red compound eyes over most of the head, the",
  "    three ocelli on the vertex, and antennae ending in a feathered",
  "    arista - the branched bristle a fly actually hears with.",
  "  - Grooms head first with the forelegs, then wings and abdomen with the",
  "    hind legs: the real anterior-to-posterior hierarchy.",
  "  - A moderate threat can freeze it solid instead of launching it. Only",
  "    a giant-fibre spike breaks the freeze.",
  "  - Walks backwards on an MDN burst.",
  "  - Sleeps on two clocks at once, the way an animal does: how long it",
  "    has been awake, and what hour it is. Naps run five to fifteen",
  "    minutes - past the immobility criterion that defines fly sleep -",
  "    and never the same length twice. At its peak it has to be nearly",
  "    spent before it will nap and sleeps about a quarter of the time; at",
  "    its trough far less will do and it sleeps over half. It wakes",
  "    grooming.",
  "  - Asleep, it settles into a crouch and is genuinely harder to rouse:",
  "    its senses are gated down, deeper the longer it sleeps, so mild",
  "    motion passes it by and only a strong threat - or a touch, or a",
  "    neighbour blundering into it - wakes it, slower than an awake fly",
  "    would move.",
  "",
  "INDIVIDUALS",
  "  - Sex, size, cuticle tone, melanisation and wing length all vary, and",
  "    all show: females larger, longer and banded to a pointed tip; males",
  "    smaller and rounder with the fused black rear, and the sex comb on",
  "    the foreleg that is how you tell a fly's sex by eye.",
  "  - Temperament varies too: rover/sitter foraging alleles (~70% rover),",
  "    a lifelong turn bias, boldness, vigor, sociability, attentiveness.",
  "  - So a crowd never moves as one. One bolts, one freezes, one never",
  "    noticed. They loosely aggregate, and shoulder each other aside.",
  "  - Same-sex meetings are aggression contests with a real winner/loser",
  "    effect. The loser stays submissive for minutes. The fight itself is",
  "    dimorphic: males lunge and the winner stands over the rout with",
  "    wings raised; females headbutt, and never show the wing threat.",
  "",
  "THE DESKTOP AS TERRAIN",
  "  - Nothing on screen is flat to something three millimetres long. A",
  "    window is a box: it climbs the side and walks the rim. An icon is a",
  "    card lying on the table. The taskbar is a kerb, a menu is the",
  "    highest thing in the room while it is open.",
  "  - Stacked windows step upward, because the one in front really is on",
  "    top. A fly standing on a rim draws a little larger and throws its",
  "    shadow down onto the desktop below it.",
  "  - It would rather perch than stand on open floor, and when it picks a",
  "    landing spot it looks at a few and takes the highest - so a pile of",
  "    windows draws it up.",
  "  - A rim is only walkable where nothing in front covers it, and the",
  "    ground vanishing underneath - a window closing, a menu dismissed -",
  "    is a fly suddenly airborne.",
  "",
  "CATCHING",
  "  - Press on a grounded fly to pin it - 36 px of reach - then hold it",
  "    down 2.6 seconds while it fights you.",
  "  - Where the grab lands decides it. Caught by the edge, a healthy fly",
  "    gets away about 9 times in 10 - it has leverage. Pinned through the",
  "    middle it has none, and you keep it about three times in four.",
  "  - Grab and let go inside about a quarter second and it leaves intact.",
  "    Hold it longer and it pays: a notched wing, permanently slower and",
  "    wobblier, and worse if it tore loose rather than being released.",
  "  - And a worn fly is a weaker fly. Every escape costs it wing, and the",
  "    next grip is harder to break. The one you have caught and lost three",
  "    times is the one you finally keep.",
  "  - It stays rattled for minutes afterwards - walking faster, slower to",
  "    settle, flinching at shapes it would have ignored. And it remembers",
  "    the spot where you caught it.",
  "  - Once it finally feels safe again it stops and washes itself, long",
  "    and hard - handled flies always do.",
  "  - Sleeping flies are easy. Alert ones usually slip you.",
  "  - Stalk it like a real fly: a slow approach does not read as a",
  "    strike, so creeping the pointer in gets you close. Lunging does",
  "    read as one, and launches it.",
  "",
  "SOUND",
  "  - Off until you ask for it, and output only. It never opens a mic.",
  "  - Each airborne fly gets its own voice at its own wingbeat frequency.",
  "    Measured in free flight, that runs 215 Hz in the smallest flies to",
  "    261 Hz in the largest - so bigger flies buzz *higher*, which is the",
  "    opposite of the usual guess. Panned to where the fly is.",
  "  - Not a tone: a fly is turbulent air chopped at the wingbeat, so the",
  "    voice is a sawtooth plus a band of hiss, modulated together at that",
  "    frequency. The rasp is the chopping. The second harmonic is carried",
  "    explicitly, because in a real fly it trades the lead with the first.",
  "  - Quiet on purpose, and calibrated rather than guessed: a fly in",
  "    flight sits near 7% of Webamp's level at Webamp's default volume.",
  "  - A caught fly buzzes in the uneven bursts of something trying to get",
  "    away from you.",
  "",
  "LIMITS",
  "  - No courtship. That is male-brain circuitry, and FAFB is a female",
  "    brain, so there is nothing honest to run.",
  "  - Nothing survives a reload. These memories live only as long as the",
  "    fly does.",
  "  - This is 9,907 of the 139,255 cells in the reconstruction, about 7%:",
  "    its reflex, compass and memory circuits, not a whole animal. It is",
  "    not sentient.",
  "  - It is, however, a real sliver of one. When it bolts from your",
  "    cursor, that decision crossed real synapses.",
];
